preço = float(input("Qual o preço do produto? R$"))
pix = preço - (preço * 15 / 100)
#Com desconto
parcela1 = preço - (preço * 10 / 100)
parcela2 = preço - (preço * 5 / 100)
parcela3 = preço - (preço * 5 / 100)
parcela4 = preço - (preço * 3 / 100)
parcela5 = preço - (preço * 3 / 100)
parcela6 = preço - (preço * 3 / 100)
#Com juros
parcela7 = preço + (preço * 2 / 100)
parcela8 = preço + (preço * 3 / 100)
parcela9 = preço + (preço * 4 / 100)
parcela10 = preço + (preço * 5 / 100)
parcela11 = preço + (preço * 6 / 100)
parcela12 = preço + (preço * 7 / 100)

print("\nO preço do produto é R${:.2f}.".format(preço))
print("R${:.2f} à vista no PIX (com 15% de desconto).".format(pix))
print("-" * 40)
print("PARCELAMENTO")
print("1x de R${:.2f} (com 10% de desconto)".format(parcela1))
print("2x de R${:.2f} (com 5% de desconto)".format(parcela2 / 2))
print("3x de R${:.2f} (com 5% de desconto)".format(parcela3 / 3))
print("4x de R${:.2f} (com 3% de desconto)".format(parcela4 / 4))
print("5x de R${:.2f} (com 3% de desconto)".format(parcela5 / 5))
print("6x de R${:.2f} (com 3% de desconto)".format(parcela6 / 6))
print("7x de R${:.2f} (com 2% de juros)".format(parcela7 / 7))
print("8x de R${:.2f} (com 3% de juros)".format(parcela8 / 8))
print("9x de R${:.2f} (com 4% de juros)".format(parcela9 / 9))
print("10x de R${:.2f} (com 5% de juros)".format(parcela10 / 10))
print("11x de R${:.2f} (com 6% de juros)".format(parcela11 / 11))
print("12x de R${:.2f} (com 7% de juros)".format(parcela12 / 12))
print("-" * 40)