n = input("Digite algo: ")
print("O tipo deste digito é:",type(n))
print("É um número?",n.isnumeric())
print("É alfabético?",n.isalpha())
print("É alfanumérico?",n.isalnum())
print("Só possui espaços?",n.isspace())
print("Está maiúsculo?",n.isupper())
print("Está minúsculo?",n.islower())
print("Se inicia com letra maiúscula?",n.istitle())