n = (input("Digite algo: "))
print("O tipo é:",type(n))
print("Só tem espaços?",n.isspace())
print("É um número?",n.isnumeric())
print("É alfabético?",n.isalpha())
print("É alfanumérico?",n.isalnum())
print("É composto por letras maiúsculas?",n.isupper())
print("É composto por letras minúsculas?",n.isupper())
print("Está capitalizada?",n.istitle())